### ISSUE TITLE
casbin自定义权限模型BUG，多个协程并发读写map，造成线程(协程)安全问题

### ISSUE THREAD

**Issue by hatch1994** [wenjianzhang/go-admin#181]
# casbin version : 2.8.7
# gorm-adapter version: 2.1.0
```bash

fatal error: concurrent map writes

goroutine 137 [running]:
runtime.throw(0xef6bbd, 0x15)
	W:/Go/src/runtime/panic.go:1116 +0x79 fp=0xc003459078 sp=0xc003459048 pc=0x436639
runtime.mapassign_faststr(0xdd72a0, 0xc002649c20, 0xc0027f8fa0, 0x20, 0xc0002a8498)
	W:/Go/src/runtime/map_faststr.go:211 +0x3fe fp=0xc0034590e0 sp=0xc003459078 pc=0x413cce
github.com/casbin/casbin/v2/persist.LoadPolicyLine(0xc000552480, 0x25, 0xc000213cb0)
	C:/Users/hatch/go/pkg/mod/github.com/casbin/casbin/v2@v2.8.7/persist/adapter.go:43 +0x522 fp=0xc003459270 sp=0xc0034590e0 pc=0xa779c2
github.com/casbin/gorm-adapter/v2.loadPolicyLine(0x0, 0x0, 0x16e1eb0, 0x1, 0xc000ebe6a0, 0x6, 0xc00092b960, 0x15, 0xc000ebe6a6, 0x3, ...)
	C:/Users/hatch/go/pkg/mod/github.com/casbin/gorm-adapter/v2@v2.1.0/adapter.go:242 +0x18b fp=0xc003459328 sp=0xc003459270 pc=0xb9216b
github.com/casbin/gorm-adapter/v2.(*Adapter).LoadPolicy(0xc0000983c0, 0xc000213cb0, 0x0, 0x0)
	C:/Users/hatch/go/pkg/mod/github.com/casbin/gorm-adapter/v2@v2.1.0/adapter.go:253 +0x1a7 fp=0xc003459468 sp=0xc003459328 pc=0xb924c7
github.com/casbin/casbin/v2.(*Enforcer).LoadPolicy(0xc00018d5e0, 0xc0027ab590, 0xeebf13)
	C:/Users/hatch/go/pkg/mod/github.com/casbin/casbin/v2@v2.8.7/enforcer.go:247 +0x5a fp=0xc0034594a8 sp=0xc003459468 pc=0xa7d08a
go-admin/pkg/casbin.Casbin(0xc000564000, 0xeebf13, 0xb)
	W:/Project/factory/go-admin/pkg/casbin/mycasbin.go:44 +0x38 fp=0xc003459500 sp=0xc0034594a8 pc=0xb95338
go-admin/middleware.AuthCheckRole.func1(0xc000564000)
	W:/Project/factory/go-admin/middleware/permission.go:18 +0x80 fp=0xc003459600 sp=0xc003459500 pc=0xbe5a30
github.com/gin-gonic/gin.(*Context).Next(0xc000564000)

```
[Casbin Map并发问题 ＃323](https://github.com/casbin/casbin/issues/323)

**Comment by hatch1994** [comment]
我尝试更改Casbin enforcer为Casbin.NewSyncedEnforcer同步加载策略lock, unlock(加锁)的做法。go-admin项目 pkg/casbin/mycasbin.go  line number #37
这也是[官方文档做法](https://casbin.org/docs/zh-CN/multi-threading)
另一种解决办法就是利用channel串行化处理

**Comment by nodece** [comment]
I made a PR to fix the issue: https://github.com/wenjianzhang/go-admin/pull/182.
